-- =========================
-- DISCOUNT
-- =========================
CREATE TABLE DISCOUNT (
    ID SERIAL PRIMARY KEY,
    CODE VARCHAR(50) NOT NULL,
    QUESTION VARCHAR(255),
    PERCENTAGE DECIMAL(5,2)
);

-- =========================
-- USER
-- =========================
CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) NOT null,
    PASSWORD VARCHAR(255) NOT NULL
);

-- =========================
-- PARTICIPANT
-- =========================
CREATE TABLE PARTICIPANT (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    SURNAME VARCHAR(100),
    BIRTHDATE DATE,
    GENDER VARCHAR(10),
    HEALTH_CARD VARCHAR(50),
    DATATREATMENT BOOLEAN,
    IMAGES BOOLEAN,
    OUTINGS BOOLEAN,
    SIBILINGS BOOLEAN,
    REPEAT BOOLEAN,
    NOTES TEXT
);

-- =========================
-- RESPONSIBLE
-- =========================
CREATE TABLE RESPONSIBLE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    SURNAME VARCHAR(100),
    DNI VARCHAR(20),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    RELATION VARCHAR(50),
    SIGNATURE BYTEA,
    AUTHORIZED BOOLEAN,
    PARTICIPANT_ID INT,
    FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANT(ID)
);

-- =========================
-- PAYMENT
-- =========================
CREATE TABLE PAYMENT (
    ID SERIAL PRIMARY KEY,
    PAYMENT_DATE DATE,
    REASON VARCHAR(255),
    IMPORT DECIMAL(10,2),
    RECEIPT BOOLEAN,
    PARTICIPANT_ID INT,
    FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANT(ID)
);

-- =========================
-- INSCRIPTION
-- =========================
CREATE TABLE INSCRIPTION (
    ID SERIAL PRIMARY KEY,
    PAYMENT_ID INT,
    RESPONSIBLE_ID INT,
    PARTICIPANT_ID INT,
    MODALITY VARCHAR(50),
    INSCRIPTION_DATE DATE,
    TOTAL DECIMAL(10,2),
    FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(ID),
    FOREIGN KEY (RESPONSIBLE_ID) REFERENCES RESPONSIBLE(ID),
    FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANT(ID)
);

-- =========================
-- SUMMERCAMP
-- =========================
CREATE TABLE SUMMERCAMP (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(150),
    PLACE VARCHAR(150),
    YEAR INT,
    STARTDATE DATE,
    WEEKS INT
);

-- =========================
-- WEEK
-- =========================
CREATE TABLE WEEK (
    CAMPAMENT_ID INT,
    WEEK_ID INT,
    NUMBER INT,
    TOTAL_PLACES INT,
    AVAILABLE_PLACES INT,
    TOTAL_PLACES_DISABLED INT,
    AVAILABLE_PLACES_DISABLED INT,
    PRIMARY KEY (CAMPAMENT_ID, WEEK_ID),
    FOREIGN KEY (CAMPAMENT_ID) REFERENCES SUMMERCAMP(ID)
);

-- =========================
-- PRICE
-- =========================
CREATE TABLE PRICE (
    CAMPAMENT_ID INT,
    WEEK_ID INT,
    BASELINE DECIMAL(10,2),
    DISABILITY DECIMAL(10,2),
    EARLY_RISE DECIMAL(10,2),
    BREAKFAST DECIMAL(10,2),
    LUNCH DECIMAL(10,2),
    PRIMARY KEY (CAMPAMENT_ID, WEEK_ID),
    FOREIGN KEY (CAMPAMENT_ID, WEEK_ID) REFERENCES WEEK(CAMPAMENT_ID, WEEK_ID)
);

-- =========================
-- SIGNED_UP
-- =========================
CREATE TABLE SIGNED_UP (
    INSCRIPTION_ID INT,
    SUMMERCAMP_ID INT,
    WEEK_ID INT,
    PRICE DECIMAL(10,2),
    LUNCH BOOLEAN,
    BREAKFAST BOOLEAN,
    EARLY_RISE BOOLEAN,
    STATE VARCHAR(50),
    PRIMARY KEY (INSCRIPTION_ID, SUMMERCAMP_ID, WEEK_ID),
    FOREIGN KEY (INSCRIPTION_ID) REFERENCES INSCRIPTION(ID),
    FOREIGN KEY (SUMMERCAMP_ID) REFERENCES SUMMERCAMP(ID),
    FOREIGN KEY (SUMMERCAMP_ID, WEEK_ID) REFERENCES WEEK(CAMPAMENT_ID, WEEK_ID)
);

-- =========================
-- EXTRAFORM
-- =========================
CREATE TABLE EXTRAFORM (
    ID SERIAL PRIMARY KEY,
    SCHOOLING_TYPE VARCHAR(100),
    SPORT BOOLEAN,
    SWIMMING BOOLEAN,
    DISABILITY BOOLEAN,
    WHEELCHAIR BOOLEAN,
    COPING_MACHANISMS TEXT,
    ROUTINE TEXT,
    EMOTIONAL_SELF_REGULATION TEXT,
    INTESTINES TEXT,
    AID TEXT,
    STAIRS TEXT,
    OUTSIDE_MOBILITY TEXT,
    CRAWLING TEXT,
    WALKING TEXT,
    JUMPING TEXT,
    PLAY_FIXATION TEXT,
    ALONE_PLAY TEXT,
    MOBILITY_AID TEXT,
    RUNNING TEXT,
    SOCIAL_PLAY TEXT,
    HAND_WASHING TEXT,
    BLADDER TEXT,
    CHOCKING TEXT,
    FOOD_SENSITIVITY TEXT,
    EATING TEXT,
    EATING_AID TEXT
);

-- =========================
-- DISABILITY
-- =========================
CREATE TABLE DISABILITY (
    ID SERIAL PRIMARY KEY,
    EXTRAFORM_ID INT,
    OB TEXT,
    DEGREE VARCHAR(50),
    DEPENDENCY VARCHAR(50),
    AID TEXT,
    CALLED BOOLEAN,
    PARTICIPANT_ID INT,
    FOREIGN KEY (EXTRAFORM_ID) REFERENCES EXTRAFORM(ID),
    FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANT(ID)
);

-- =========================
-- MEDICATIONS
-- =========================
CREATE TABLE MEDICATIONS (
    MEDICATION VARCHAR(255),
    PARTICIPANT_ID INT,
    PRIMARY KEY (MEDICATION, PARTICIPANT_ID),
    FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANT(ID)
);

-- =========================
-- ALLERGIES
-- =========================
CREATE TABLE ALLERGIES (
    ALLERGY VARCHAR(255),
    PARTICIPANT_ID INT,
    PRIMARY KEY (ALLERGY, PARTICIPANT_ID),
    FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANT(ID)
);

-- =========================
-- FEARS
-- =========================
CREATE TABLE FEARS (
    FEAR VARCHAR(255),
    EXTRAFORM_ID INT,
    PRIMARY KEY (FEAR, EXTRAFORM_ID),
    FOREIGN KEY (EXTRAFORM_ID) REFERENCES EXTRAFORM(ID)
);

-- =========================
-- SPORTS
-- =========================
CREATE TABLE SPORTS (
    SPORT VARCHAR(255),
    EXTRAFORM_ID INT,
    PRIMARY KEY (SPORT, EXTRAFORM_ID),
    FOREIGN KEY (EXTRAFORM_ID) REFERENCES EXTRAFORM(ID)
);

CREATE TABLE ADDRESS (
    ID SERIAL PRIMARY KEY,
    PC VARCHAR(10),
    STREET VARCHAR(150),
    CITY VARCHAR(100),
    PROVINCE VARCHAR(100),
    PARTICIPANT_ID INT,
    FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANT(ID)
);
CREATE TABLE COMMUNICATION (
    ID SERIAL PRIMARY KEY,
    LANGUAGE TEXT,
    IMITATION TEXT,
    COMPREHENSION TEXT,
    WRITING TEXT,
    READING TEXT,
    ORAL TEXT,
    EXTRAFORM_ID INT,
    FOREIGN KEY (EXTRAFORM_ID) REFERENCES EXTRAFORM(ID)
);